from purequant.trade.okexspot import OKEXSPOT
from purequant.trade.okexfutures import OKEXFUTURES
from purequant.trade.okexswap import OKEXSWAP
from purequant.trade.huobispot import HUOBISPOT
from purequant.trade.huobifutures import HUOBIFUTURES
from purequant.trade.huobiswap import HUOBISWAP
from purequant.trade.binancespot import BINANCESPOT
from purequant.trade.binancefutures import BINANCEFUTURES
from purequant.trade.binanceswap import BINANCESWAP
from purequant.trade.bitmex import BITMEX
from purequant.trade.bitmexws import BITMEXWS
from purequant.trade.ccxt_exchanges import CCXTEXCHANGE
from purequant.trade.bitcoke import BITCOKE
from purequant.trade.mxc import MXC
from purequant.trade.bybitfutures import BYBITFUTURES
from purequant.trade.bybitswap import BYBITSWAP